// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderFoodTeam;

namespace OrderFoodTeam.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191205233400_quan")]
    partial class quan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderFoodTeam.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("OrderFoodTeam.Models.Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("OrderFoodTeam.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Clientid")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Tableid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Clientid");

                    b.HasIndex("Tableid");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("OrderFoodTeam.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Imageid")
                        .HasColumnType("int");

                    b.Property<int>("Measurement")
                        .HasColumnType("int");

                    b.Property<byte>("MeasurementEnum")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<byte>("ProductEnum")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.HasIndex("Imageid");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("OrderFoodTeam.Models.Table", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Reserved")
                        .HasColumnType("bit");

                    b.Property<int>("SeatsQuantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("OrderFoodTeam.Models.Order", b =>
                {
                    b.HasOne("OrderFoodTeam.Models.Client", "Client")
                        .WithMany("Order")
                        .HasForeignKey("Clientid");

                    b.HasOne("OrderFoodTeam.Models.Table", "Table")
                        .WithMany("Order")
                        .HasForeignKey("Tableid");
                });

            modelBuilder.Entity("OrderFoodTeam.Models.Product", b =>
                {
                    b.HasOne("OrderFoodTeam.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("Imageid");
                });
#pragma warning restore 612, 618
        }
    }
}
